import os

print("GOOGLE_APPLICATION_CREDENTIALS:", os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))
print("VERTEX_PROJECT_ID:", os.getenv("VERTEX_PROJECT_ID"))
print("VERTEX_LOCATION:", os.getenv("VERTEX_LOCATION"))
